###
GET localhost:8080/api/search/article?q=javascript

###
GET localhost:8080/api/search/article?q=indexes

###
GET localhost:8080/api/search/article?q=Functional programming

###
GET localhost:8080/api/search/article?q=Functional&stem=0