GET localhost:8080/api/search/twitter?q=gorgeous

###
GET localhost:8080/api/search/twitter?q=helping&stem=false

###
GET localhost:8080/api/search/twitter?q=funny joke

###
GET localhost:8080/api/search/twitter?q=Jumped

###
GET localhost:8080/api/search/twitter?q=ipl&n=6

###
GET localhost:8080/api/search/user/aDeSe

###
GET localhost:8080/api/search/twitter/count

###
GET localhost:8080/api/search/twitter?q=ipl&from=azulfi

###
GET localhost:8080/api/search/twitter?q=joke&from=princesschrysti

###
GET localhost:8080/api/search/twitter?q=try&from=icyblue93
###
GET localhost:8080/api/search/twitter?q=tried
###
GET localhost:8080/api/search/twitter?q=trying