GET localhost:8080/api/search/twitter?q=god

###
GET localhost:8080/api/search/twitter?q=luck

###
GET localhost:8080/api/search/twitter?q=funny joke

###
GET localhost:8080/api/search/twitter?q=Jumped

###
GET localhost:8080/api/search/twitter?q=ipl

###
GET localhost:8080/api/search/user/aDeSe

###
GET localhost:8080/api/search/twitter/count

###
GET localhost:8080/api/search/twitter?q=ipl&from=azulfi

###
GET localhost:8080/api/search/twitter?q=joke&from=princesschrysti